### ISSUE TITLE
Either move to svelte or django

### ISSUE THREAD

**Issue by redstone-dev** [redstone-dev/Snazzle#2]
We need to move to svelte or django, because right now this is a cobbled-together flask project, it works well for small-scale stuff but I wanted to hammer out a prototype before we flesh it out in Django/svelte.

Either that or we could stick with Flask

**Comment by Darth-Ness** [comment]
I think we should just stick to Flask. You already have a nice code base, and we should move forward on features like the forums and being able to play projects instead of rewriting things that work perfectly fine. If you must change the framework, I wouldn't do Svelte. So at least you could keep it in the same language.

**Comment by EngineerRunner** [comment]
i agree with sticking with Flask, at least until we have most site features working.

**Comment by redstone-dev** [comment]
We'll stick with flask for now
